### ISSUE TITLE
Add fluent mechanism to construct encoded uri parameters using QueryStringEncoder

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor-netty#1058]
## Motivation
Currently, when making a HttpClient request, the fluent api expects the URI to be single string. This leads to ugly url string concatanation & also the API does not give a hint whether the underlying library would escape URI appropriately/it expects the user to do the escaping

## Desired solution
Add an overload of uri that allows users to consurtct uri in a fluent manner. One potential implementation detail would be to use `QueryStringEncoder` from netty internally and expose a fluent API to the user, the same way we currently do for `headers`

With fluent API user can be certain that the encoding is done for sure & also he has a saner way of constructing the uri parameters

**Comment by violetagg** [comment]
I'm closing this issue as `uri(URI)` provides the requested functionality. Reactor Netty users can choose which library to use in order to construct the needed URI (for example #1323 where `QueryStringEncoder` is used). 
If there is a broader interest for something like `uri(UriBuilder)` we can reopen the issue and discuss the further steps.
