### ISSUE TITLE
Setting h2c max content length on HttpRequestDecoderSpec does not work

### ISSUE THREAD

**Issue by mkozioro** [reactor/reactor-netty#1143]
Setting h2c max content length does not change anything. I'm setting it in a way:
```
@SpringBootApplication
@EnableWebFlux
public class RestServerApplication {
    private static final int H2C_MAX_CONTENT_LENGTH = 50_000;

    @Bean
    NettyServerCustomizer h2cCustomizer() {
        return httpServer -> httpServer.protocol(HttpProtocol.H2C, HttpProtocol.HTTP11)
                .httpRequestDecoder(spec -> spec.h2cMaxContentLength(H2C_MAX_CONTENT_LENGTH));
    }

    public static void main(String[] args) {
        SpringApplication.run(RestServerApplication.class, args);
    }
}
```

Support for that functionality was added in https://github.com/reactor/reactor-netty/pull/1072/

## Expected Behavior

Curl request should not return 413 error. 

## Actual Behavior
I'm receiving 413 error.

## Steps to Reproduce

```
curl --http2 -v --request POST   --url http://localhost:8080/echo   --header 'content-type: application/json'   --data '{"message": "Hello"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /echo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
> content-type: application/json
> Content-Length: 20
> 
* upload completely sent off: 20 out of 20 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 413 Request Entity Too Large
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

## Your Environment

* Reactor version(s) used: 0.9.7.RELEASE
* Spring Boot: 2.3.0
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.49
* JVM version (`javar -version`): OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
* OS and version (eg `uname -a`): Ubuntu 20.04

**Comment by mkozioro** [comment]
It works properly, but must be set differently. I found working:

```
@SpringBootApplication
@EnableWebFlux
public class RestServerApplication {
    private static final int H2C_MAX_CONTENT_LENGTH = 50_000;

    @Bean
    NettyServerCustomizer nettyServerCustomizer() {
        return httpServer -> httpServer.protocol(HttpProtocol.H2C, HttpProtocol.HTTP11);
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    WebServerFactoryCustomizer<NettyReactiveWebServerFactory> contentLengthCustomizer() {
        return factory -> factory.addServerCustomizers(
                httpServer -> httpServer.httpRequestDecoder(spec -> spec.h2cMaxContentLength(H2C_MAX_CONTENT_LENGTH)));
    }

    public static void main(String[] args) {
        SpringApplication.run(RestServerApplication.class, args);
    }
}
```

Maybe there is some better way to set this.

**Comment by violetagg** [comment]
@mkozioro You observe this behaviour because by default there is a customiser that configures the http request decoder.
https://github.com/spring-projects/spring-boot/blob/13564b4a13021b39be604f73467b2e94fa672d42/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/NettyWebServerFactoryCustomizer.java#L78-L81

So what happens
- You configure H2C max content length (using `NettyServerCustomizer`)
- Then the default customiser overrides your setting.

In order to solve this issue you should use also a customiser (using `WebServerFactoryCustomizer<NettyReactiveWebServerFactory>`)
https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/html/howto-embedded-web-servers.html#howto-configure-webserver

So that you will be able to override the default customiser.

This is not Reactor Netty issue.
