### ISSUE TITLE
PatternSyntaxException on nonProxyHosts

### ISSUE THREAD

**Issue by nhomble** [reactor/reactor-netty#1190]
I am porting my existing application that defines nonProxyHosts with the patterns described in [Oracle: Networking Properties](https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html) but the netty client is throwing parsing errors.

## Expected Behavior

The clients proxy selector should understand ```*``` as a wildcard despite not being a normal regex like ```.*```

An example value is ```"*.some.domain"```

## Actual Behavior

```PatternSyntaxException``` is thrown in ```ProxyProvider``` when ```Pattern.compile(builder.nonProxyHosts, 2)``` is executed.

## Steps to Reproduce
https://github.com/nhomble/repro-netty-nonproxyhosts-pattern

## Possible Solution

~~We could massage the string before compiling and replace ```*``` with ```.*```~~
We can't do a simple replace on wildcards without also considering the periods in the domain name.

Given their exist users who depend on the regex approach, we could either break compatibility or introduce another method on the builder to accept the selector ourselves rather than take the pattern as a string and let reactor-netty compile it internally

**Comment by violetagg** [comment]
@nhomble 
https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/ProxyProvider.Builder.html#nonProxyHosts-java.lang.String-

```
Regular expression (using java.util.regex) for a configured list of hosts that should be reached directly, bypassing the proxy.
```

This is not just a pattern but gives you the possibility to create a regular expression for hosts that will bypass the proxy.
Reactor Netty will use the regular expression that is provided by the user.

**Comment by nhomble** [comment]
I agree the docs make it clear that netty expects a regular expression, so maybe this is less of a bug in the code but I think a bug in the expectations many people would have when configuring their proxies. To quote from the oracle doc
```text
For example -Dhttp.nonProxyHosts=”*.foo.com|localhost” will indicate that every hosts in the foo.com domain and the localhost should be accessed directly even if a proxy server is specified.
```

won't work because of the dangling metacharacter ```*``` in the beginning

**Comment by violetagg** [comment]
@nhomble yep as it is not a valid regular expression.
If we provide an API like this will it solve your issue `Builder nonProxyHosts(Predicate<SocketAddress> nonProxyHostsPredicate);`

**Comment by nhomble** [comment]
@violetagg thanks, I think that moves us in the right direction and this is definitely extensible. Is it worthwhile for the project to own some parser to translate the nonProxyHosts pattern into a predicate?

**Comment by violetagg** [comment]
@nhomble May be as part of the #887 ?

**Comment by lion7** [comment]
@violetagg this issue still seems to be present in version 5.3.10.

For example the code following code wil fail:
`HttpClient.create().proxyWithSystemProperties()`
When the JVM is started with `java -Dhttp.nonProxyHosts=*.googleapis.com -jar example.jar`.

The exception:
`java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0 in '*.googleapis.com'`

To me it seems that the `RegexShouldProxyPredicate fromWildcardedPattern(String pattern)` method should be used when the input is a pattern as described in Oracle's documentation. The entire call hierarchy:
![image](https://user-images.githubusercontent.com/5264897/141101056-c0c3bed8-4913-4f03-b574-c04c30c4e4df.png)

**Comment by sebphil** [comment]
I have the exact same issue that @lion7 mentioned. I'm using reactor-netty-core:1.0.13

I believe the problem lies in how `ProxyProvider.createHttpProxyFrom(Properties properties)` handles the http.nonProxyHosts system property. Since netty uses the "standard" name for this property, as described in the Oracle docs, I think netty should assume the "standard" format is used too. It means that the nonProxyHosts property should be parsed as a wildcarded String and not a regex when it comes from system properties.

Even the default value provided by netty has a wildcard format and is not a regex: `static final String DEFAULT_NON_PROXY_HOSTS = "localhost|127.*|[::1]";`, but it is parsed as a regex all the same. It only happens that this default value does not crash the regex parser, but it is **not** a good regex.

I think that the ProxyProvider built at the end of `ProxyProvider.createHttpProxyFrom(Properties properties)` should be changed this way: replace `.nonProxyHosts(nonProxyHosts)` with `.nonProxyHostsPredicate(RegexShouldProxyPredicate.fromWildcardedPattern(nonProxyHosts))`

@violetagg would you rather have this issue reopened or another one created? I'm willing to provide a PR with the fix I mentioned.

**Comment by violetagg** [comment]
@sebphil Can you try the current 1.0.14-SNAPSHOT?
See #1861

**Comment by sebphil** [comment]
Thank you for your quick reply. 1.0.14-SNAPSHOT effectively solves this issue.
