### ISSUE TITLE
How to properly use connection pool  for Httpclient?

### ISSUE THREAD

**Issue by scj7508** [reactor/reactor-netty#1227]
Even though I create individaul ConnectionProvider , I found the channel will auto dispose later which I think the channel should be cached .  how to properly use connection pool  for Httpclient in a springmvc applicatoin?

```

@Test
    public void test2(){
        ConnectionProvider poolConnectionProvider = ConnectionProvider
                .builder("myTest")
                .maxConnections(1)
                .build();

        System.out.println(">>>>>>>>>>>round 1>>>>>>>>>>>");
        get(poolConnectionProvider);
        System.out.println(">>>>>>>>>>>round 2>>>>>>>>>>>");
        get(poolConnectionProvider);
    }
private void get(ConnectionProvider connectionProvider){
        String response =
                HttpClient
                        .create(HttpResources.set(connectionProvider))
                        .wiretap(true)
                        .observe((connection, newState) -> System.out.println("State:"+newState))
                        .disableRetry(true)
                        .get()
                        .uri(TEST_URL)
                        .responseContent()
                        .aggregate()
                        .asString()
                        .block();
    }
```

![image](https://user-images.githubusercontent.com/16132707/88631834-5fb4e400-d0e5-11ea-9f17-00ab029a3217.png)
![image](https://user-images.githubusercontent.com/16132707/88631878-7824fe80-d0e5-11ea-82a3-50431dd392e2.png)

**Comment by violetagg** [comment]
@scj7508 You see this behaviour because you always **preset** the **global** `ConnectionProvider`. When you invoke `HttpResources.set` we dispose the current `ConnectionProvider` and set the new one. You should have the following warning in the logs

```
11:47:28.153 [Test worker] WARN  reactor.netty.tcp.TcpResources - [http] resources will use a new ConnectionProvider: reactor.netty.resources.DefaultPooledConnectionProvider@d7b1bcc,the previous ConnectionProvider will be disposed
```

In Reactor Netty there is a notion for global resources and local resources.

If you want to set a `ConnectionProvider` as a global you need to invoke the code `HttpResources.set(poolConnectionProvider);` just once.

If you want to set a `ConnectionProvider` per client you need to create the client like this `HttpClient.create(poolConnectionProvider)`.

I changed your code to set just once the global `ConnectionProvider`, now you will be able see that the connection is reused.

```
@Test
public void test2(){
	ConnectionProvider poolConnectionProvider = ConnectionProvider
			.builder("myTest")
			.maxConnections(1)
			.build();

	HttpResources.set(poolConnectionProvider);
	System.out.println(">>>>>>>>>>>round 1>>>>>>>>>>>");
	get();
	System.out.println(">>>>>>>>>>>round 2>>>>>>>>>>>");
	get();
}

private void get(){
	String response =
			HttpClient
					.create()
					.wiretap(true)
					.observe((connection, newState) -> System.out.println("State:"+newState))
					.disableRetry(true)
					.get()
					.uri("http://example.com/")
					.responseContent()
					.aggregate()
					.asString()
					.block();
}
```

**Comment by scj7508** [comment]
Thank you very much

**Comment by scj7508** [comment]
@violetagg thank you
