### ISSUE TITLE
reactor.ipc.netty.http.client.HttpClient and nonProxyHosts

### ISSUE THREAD

**Issue by mehmetsalgar** [reactor/reactor-netty#123]
Hi,

I am trying to evaluate Spring Webflux 2.0.0.M2 for one of our use cases, WebFlux internally uses 'reactor.ipc.netty.http.client.HttpClient' to configure the WebClient  with the following code snippet.

private WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(options -> options.preferNative(false))).build();

Unfortunately during my evaluations, I found that it is not possible to configure 'nonProxyHosts' for HttpClient (I didn't configured any proxy for the Webclient, probably it finds out over operating system configuration values), for test purposes, if I try to call an URL in localhost, it tries to resolve it over the proxy server and naturally it fails.

Is there a way to configure 'nonProxyHosts' if not could it be implemented?

**Comment by violetagg** [comment]
Hi,

By default a proxy is not applied if it is not configured. You can see here [1] how one can configure a proxy.
Most probably your problem lies somewhere else. You can switch the log level for `reactor.ipc.netty` to `DEBUG` in order to inspect the traffic.

Regards,
Violeta

[1] https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java#L228

**Comment by simonbasle** [comment]
link to related issue in boot: spring-projects/spring-boot#9676

**Comment by simonbasle** [comment]
As @bclozel said in the boot issue you opened:
> I'm not even aware of Netty / Reactor Netty supporting JDK style http.* environment variables. As far as I know, those libraries don't use the HTTP stack in java.net.

**Comment by simonbasle** [comment]
Opened #125 to add the feature of proxy bypassing to reactor.
