### ISSUE TITLE
http server tcp.metric(true) should not expose remote_address

### ISSUE THREAD

**Issue by jtorkkel** [reactor/reactor-netty#1320]
tcp.metrics(true) currently expose remote_address. This result OOM and cardinality issues.

reactor_netty_tcp_server_data_received_bytes_count{app="xxx",host="YYY",remote_address="127.0.0.1:45935",uri="tcp"} 2.0
reactor_netty_tcp_server_data_received_bytes_sum{app="xxx",host="YYY",remote_address="127.0.0.1:45935",uri="tcp"} 1292.0
reactor_netty_tcp_server_data_received_bytes_count{app="xxx",host="YYY",remote_address="127.0.0.1:45951",uri="tcp"} 2.0
reactor_netty_tcp_server_data_received_bytes_sum{app="xxx",host="YYY",remote_address="127.0.0.1:45951",uri="tcp"} 1292.0

Similar that  [#1075 Server metrics cardinality explosion](https://github.com/reactor/reactor-netty/issues/1075) 

Normal springboot2 http_server metrics are enabled and tcp.metrics enabled using code below

@Configuration
public class WebServerCustomizer {

    @Bean
    public WebServerFactoryCustomizer serverFactoryCustomizer() {
        return new NettyTimeoutCustomizer();
    }

    class NettyTimeoutCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
        @Override
        public void customize(NettyReactiveWebServerFactory factory) {
            int five = 5000;
            factory.addServerCustomizers(server -> server.tcpConfiguration(tcp ->
                    tcp.metrics(true).option(ChannelOption.CONNECT_TIMEOUT_MILLIS, five)
                            .doOnConnection(connection ->
                                    connection
                                            .addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS))
                                            .addHandlerLast(new ReadTimeoutHandler(20000, TimeUnit.MILLISECONDS))
                            )));
        }
    }
}

Reactor version(s) used: 0.9.10
JVM version (`java -version`): 8
OS and version (eg. `uname -a`): Windows 10

**Comment by violetagg** [comment]
@jtorkkel And why you enable the metrics on the TCP level and not on the HTTP level (where this use case was explicitly fixed by the linked issue)?
Note that with the upcoming 1.0.0 release you won't be able to do that exactly because of that configuration that you have in the example.

**Comment by jtorkkel** [comment]
@violetagg, 
Few reason:
1. I did not managed to enable them, thanks for the tip how to enable them. This did not work. factory.addServerCustomizers(server -> server.metrics(true, s -> s).tcpConfiguration    ....
2. in the past we had cardinality issues in reactor_netty_http_client and thus we use end up using reactor_netty_tcp_client ... tcp level expose less duplicate metrics, http metrics has same metrics as standard micrometer exposed metrics.

I think you should remove the remote_adddress <port> from reactor_netty_tcp_server 
 to eliminate the cardinality issues.

**Comment by violetagg** [comment]
@jtorkkel 

> @violetagg,
> Few reason:
> 
> 1. I did not managed to enable them, thanks for the tip how to enable them. This did not work. factory.addServerCustomizers(server -> server.metrics(true, s -> s).tcpConfiguration    ....

Is it working now?

> 2. In the past we had cardinality issues in reactor_netty_http_client and thus we use end up using reactor_netty_tcp_client_*. tcp level expose less metrics and does not have uri dimension. response time and uri dimension result larger set of metrics and partially overlap with micrometer micrometer exposed http server metrics.

You mean http client or http server metrics are exposed by micrometer?

> 3. reactor.netty.http.server.tls.handshake.time missing

Yes it is missing in HTTP because TLS handshake is done once when a connection between a client and a server is established. When you do not have `remote_address` in the metrics you can see some time but you will not know with which clients the handshake is OK and with which not.

> 
> I think you should remove the remote_adddress from reactor_netty_tcp_server
> to eliminate the cardinality issues.

If we remove the `remote_address` from tcp server metrics then they are useless
- you will have TLS time but without `remote_address` there is no info which clients are OK and which not
- you have error but no information for which clients these errors apply
- you will have data received/sent but only for TCP protocol as a whole

If you need an overall statistics with no information for the `remote_address` you can easily provide a custom recorder and expose that in Micrometer
Here is information how you can provide a custom recorder
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics

**Comment by violetagg** [comment]
@jtorkkel I'm closing this as there is not author response.
