### ISSUE TITLE
HttpClient cannot be configured with both HTTP11 and H2

### ISSUE THREAD

**Issue by dvoloshyn** [reactor/reactor-netty#1394]
## Expected Behavior

HttpClient should be able to automatically select HTTP2 for https if supported or HTTP1.1 for both http and https.

## Actual Behavior

When I configure HttpClient with .protocol(HTTP11, H2) it fails when connecting to http URLs with IllegalArgumentException("Configured H2 protocol without TLS. Use H2 Clear-Text protocol via HttpClient#protocol or configure TLS via HttpClient#secure") 

## Steps to Reproduce

1. Configure HTTP client with SSL context and .protocol(HTTP11, H2)
2. Try to send request to http URLs 

## Possible Solution

Here is the code fragment from HttpClientConnect.MonoHttpConnect with my comments
```java
                               if (handler.toURI.isSecure()) {
					if (_config.sslProvider == null) {
						_config = new HttpClientConfig(config);
						_config.sslProvider = HttpClientSecure.defaultSslProvider(_config);
					}
				}
				else {
					if (_config.sslProvider != null) {
						_config = new HttpClientConfig(config);
						_config.sslProvider = null;//We clear sslProvider for http URLs
					}
				}

				if (_config.sslProvider != null) {
					if (_config.sslProvider.getDefaultConfigurationType() == null) {
						if ((_config._protocols & HttpClientConfig.h2) == HttpClientConfig.h2) {
							_config.sslProvider = SslProvider.updateDefaultConfiguration(_config.sslProvider,
									SslProvider.DefaultConfigurationType.H2);
						}
						else {
							_config.sslProvider = SslProvider.updateDefaultConfiguration(_config.sslProvider,
									SslProvider.DefaultConfigurationType.TCP);
						}
					}

					if ((_config._protocols & HttpClientConfig.h2c) == HttpClientConfig.h2c) {
						sink.error(new IllegalArgumentException(
								"Configured H2 Clear-Text protocol with TLS. " +
										"Use the non Clear-Text H2 protocol via HttpClient#protocol or disable TLS " +
										"via HttpClient#noSSL()"));
						return;
					}
				}
				else {
                                        //This check should only be done for HTTPS URLs. We can configure multiple supported protocols besides H2
					if ((_config._protocols & HttpClientConfig.h2) == HttpClientConfig.h2) {
						sink.error(new IllegalArgumentException(
								"Configured H2 protocol without TLS. Use H2 Clear-Text " +
										"protocol via HttpClient#protocol or configure TLS via HttpClient#secure"));
						return;
					}
				}
```

## Your Environment

* Reactor version(s) used: 
Maven:io.projectreactor.netty:reactor-netty-core:1.0.1 
Maven: io.projectreactor.netty:reactor-netty-http:1.0.1 
Maven: io.projectreactor:reactor-core:3.4.0

* Other relevant libraries versions (eg. `netty`, ...):netty 4.1.54.Final
* JVM version (`java -version`):Oracle 11.0.4
* OS and version (eg. `uname -a`):Windows 10

**Comment by jGleitz** [comment]
We are also hitting this bug. For us, it means that updating to Spring Boot 2.4.0 is effectively a breaking change. We will avoid updating until this bug is fixed.

Is there anything we can do to help to get this fixed? From my point of view, @dvoloshyn’s analysis is spot-on and creating a fix should therefore be easy.

**Comment by violetagg** [comment]
@jGleitz What do you mean with breaking change? HTTP/2 for the HttpClient first support is in Reactor Netty 1.0.0/Spring Boot 2.4.0?

**Comment by jGleitz** [comment]
@violetagg interesting.

We have this piece of code to configure the `ExchangeFunction` that will be used throughout our applications:

```java
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.http.client.reactive.ReactorResourceFactory;
import org.springframework.web.reactive.function.client.ExchangeFunction;
import static reactor.netty.http.HttpProtocol.H2;
import static reactor.netty.http.HttpProtocol.HTTP11;

...

    @Bean
    @Autowired
    public ExchangeFunction exchangeFunction(
        ReactorResourceFactory resourceFactory,
        RequestsDefaults requestsDefaults
    ) {
        return ExchangeFunctions.create(new ReactorClientHttpConnector(resourceFactory, client ->
            client
                .protocol(H2, HTTP11)
                .secure()
                // more configuration
       }
```

With Spring 2.3.x, this code worked, at least insofar as we could make connections to HTTP endpoints with and without `TLS`. Does “HTTP/2 for the HttpClient first support is in Reactor Netty 1.0.0/Spring Boot 2.4.0?” mean that the client was never actually able to use H2?

With “breaking change” I was referring to the fact that this code did not produce an error previously, but does now. I our exchange function never actually used H2, then it’s still a breaking change, albeit a less severe one, since we can simply remove the `H2` part without loss of functionality.

**Comment by violetagg** [comment]
> With Spring 2.3.x, this code worked, at least insofar as we could make connections to HTTP endpoints with and without `TLS`. Does “HTTP/2 for the HttpClient first support is in Reactor Netty 1.0.0/Spring Boot 2.4.0?” mean that the client was never actually able to use H2?

In versions prior Reactor Netty 1.0.0/Spring Boot 2.4.0, HTTP/2 for the HttpClient is not supported. It is only supported for HttpServer.

> 
> With “breaking change” I was referring to the fact that this code did not produce an error previously, but does now. If our exchange function never actually used H2, then it’s still a breaking change, albeit a less severe one, since we can simply remove the `H2` part without loss of functionality.

I will strongly recommend if you do not use HTTP/2 to remove it, otherwise every time the client will try to do an application negotiation for the protocol that will be used.

**Comment by jGleitz** [comment]
> I will strongly recommend if you do not use HTTP/2 to remove it, otherwise every time the client will try to do an application negotiation for the protocol that will be used.

Can you please elaborate on why I would not want this? I was under the impression that a client that supports HTTP/2 will not cause significant overhead against a server that does not support HTTP/2, because the server will simply ignore the `Upgrade` header and communication will continue over HTTP/1.1. Likewise, if the server supports HTTP/2, it will upgrade the connection together with the response. Because of this, I was under the impression that enabling HTTP/2 together with HTTP/1.1 was a sensible choice when talking to multiple servers of which some support HTTP/2 while others don’t.

> In versions prior Reactor Netty 1.0.0/Spring Boot 2.4.0, HTTP/2 for the HttpClient is not supported. It is only supported for HttpServer.

Okay, so the option was simply ignored without an error? Surprising!

Regardless of the previous, I’d like to submit for this bug’s triage that it broke our previously not-error-throwing code.

**Comment by violetagg** [comment]
> Can you please elaborate on why I would not want this?

The current implementation is
- HTTP/1.1 with TLS or HTTP/2 with TLS, then we have application negotiations which protocol the server supports
- HTTP/1.1 without TLS or HTTP/2 clear text - here an `Upgrade` header will be used and depending on what is supported by the server, the header will be ignored for HTTP/1.1 or the header will be taken into consideration and we will continue the communication using HTTP/2 clear text.

**Comment by violetagg** [comment]
@dvoloshyn @jGleitz PTAL #1403

**Comment by jGleitz** [comment]
Thanks for the fast turnaround! :+1:

Are there plans regarding when to release version `1.0.2`?

**Comment by violetagg** [comment]
@jGleitz The tentative date is next Monday
