### ISSUE TITLE
Reactor netty metrics shows remote_address with random ports

### ISSUE THREAD

**Issue by sukawanth** [reactor/reactor-netty#1415]
Hi, we are using spring cloud gateway 2.2.3 and we have enabled reactor netty metrics. In our lab we are seeing that netty produces huge number of metrics even when there are limited number of connections which we verified using netstat.

Any clue what could be causing this issue...?

attachment: metrics exported from prometheus.
[metrics_prometheus.txt](https://github.com/reactor/reactor-netty/files/5667017/metrics_prometheus.txt) 

## Steps to Reproduce
factory.addServerCustomizers(builder -> builder.tcpConfiguration(tcpServer -> tcpServer.metrics(true)));

## Your Environment
we have deployed it in Kubernetes cluster.
 
*  Reactor netty: 0.9.8
*  Netty: 4.1.50
* JVM version : 14

**Comment by violetagg** [comment]
@sukawanth The information for the remote address is taken from the connection so can you verify how many connections from IP `10.233.117.0` were opened?
It is possible that the connection is opened and short after that closed and because of that you do not see a large number of remote connections on Spring Gateway?

**Comment by violetagg** [comment]
@sukawanth Were you able to check the suggestions in my previous comment?

**Comment by violetagg** [comment]
Closing this issue as there is no response from the author.
