### ISSUE TITLE
Spring Webflux - Not able to get "reactor.netty.http.client.data*" metrics

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#1525]
Hello Reactor Netty Team,

Just wanted to state a small observation, hope not to trouble.

With my 2.4.2 Spring Webflux app, I am currently able to get metrics such as: 
```reactor.netty.connection.provider*``` and ```reactor.netty.bytebuf.allocator.used*``` metrics.

However, I am unable to get the ```reactor.netty.http.client.data*``` metrics.

I do have the following in my code:

```
Schedulers.enableMetrics();
```

```
 @Bean
    public NettyServerCustomizer nettyServerCustomizer() {
        return httpServer -> httpServer.metrics(true, () -> new MicrometerChannelMetricsRecorder("MY_SERVICE", "MY_SERVICE"));
    }
```

And I am constructing my ReactorClientHttpConnector this way:

```
    public ReactorClientHttpConnector getReactorClientHttpConnector() {
        return new ReactorClientHttpConnector(HttpClient.create().wiretap(true).metrics(true, () -> new MicrometerChannelMetricsRecorder("myservicename", "myservicename")).secure(sslContextSpec -> sslContextSpec.sslContext(getSslContextBuilder())));
    }
```

And with such, I was expected to get all three types of metrics described here:
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_5

May I ask if my understanding is wrong, Or if I am doing anything wrong please?

Thank you

**Comment by violetagg** [comment]
@patpatpat123 You need different name in the registry, is this why you use

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Supplier-

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Function-

`Micrometer*Recorder` are not intended to be used by users that's why only `MicrometerChannelMetricsRecorder` and `MicrometerHttpMetricsRecorder`, but not `MicrometerHttpClientMetricsRecorder` and `MicrometerHttpServerMetricsRecorder`

**Comment by patpatpat123** [comment]
Hello @violetagg ,

Many thanks for the answer.

Based on what you are saying, I believe the root cause of me not seeing the "reactor.netty.http.client.data*" metrics is because I configured the ReactorClientHttpConnector wrong.

Probably due to my misunderstanding, I just used this:
```
.metrics(true, () -> new MicrometerChannelMetricsRecorder("myservicename", "myservicename"))
```

What would be a correct way to configure it please? I am a bit lost between all the possible ```Micrometer???MetricsRecorder```

Apologies for the trouble

**Comment by violetagg** [comment]
@patpatpat123 Can you try `.metrics(true, Function.identity())`?

**Comment by patpatpat123** [comment]
Indeed @violetagg ,

I am now able to see the reactor.netty.http.client.data* data, and they are very helpful.

Went through a lot of docs and couldn't find anything regarding ```.metrics(true, Function.identity())```, your comment was very very helpful.

Good day!

**Comment by violetagg** [comment]
@patpatpat123 
Nice that everything is working.
Take a look at the example here
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_5

the difference is that the example doesn't use `Function.identity()` but provides another function.

**Comment by ruslan-belinskyy** [comment]
now link above (https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_5) leads to:
```
ConnectionProvider.builder("custom")
	.maxConnections(50)
	.metrics(true) 
	.build();
```
and this method doesn't provide metrics needed (at least in my case), because when you'll debug metrics recorder will be `null` here:
https://github.com/reactor/reactor-netty/blob/6dcc3d6361737da3b4e97ed2e5df9f58546b7a28/reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java#L375

It's not clear why so many steps has to be performed to enable metrics. 
For example http server metrics can be easily enabled (Kotlin):
```
return NettyServerCustomizer { httpServer: HttpServer ->
            httpServer.metrics(
                true,
                Supplier<ChannelMetricsRecorder> {
                    reactor.netty.channel.MicrometerChannelMetricsRecorder(
                        "my-service",
                        "my-service"
                    )
                }
            )
        }
```

While http client requires:
```
Supplier<? extends ConnectionProvider.MeterRegistrar>
```
and the only implementation is MicrometerPooledConnectionProviderMeterRegistrar (which i can find), but it has private constructor and INSTANCE is protected, so no chance to use it. 

It's sad that code has to be that complicated.

**Comment by ruslan-belinskyy** [comment]
Just small clarification for above, had to spent a day to find this out but might be helpful (or someone will clarify if i'm wrong).
When it comes to HttpClient metrics can be enabled for pool:
```
val httpClient = HttpClient.create(
                ConnectionProvider.builder(builderName)
                    .metrics(config.metricsEnabled) // --> enabled here
                    .build()
            )
```
And HttpClient has other metric recorders like mentioned above which will be triggered depending which httpClient method you'll call:
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Function-
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Supplier-
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Supplier-java.util.function.Function-
The logic what will be enabled in which case is not clear for me, but some of the magic explained in this post:
https://github.com/reactor/reactor-netty/issues/1525#issuecomment-787867744

This is how full code snippet worked for me:
```
val httpClient = HttpClient.create(
                ConnectionProvider.builder(builderName)
                    .metrics(config.metricsEnabled) // --> enabled here
                    .build()
            )
httpClient.metrics(true, java.util.function.Function<String, String> { it })

```

And of course limiting:
```
init {
            Metrics.globalRegistry
                .config()
                .meterFilter(
                    MeterFilter.maximumAllowableTags(
                        HTTP_CLIENT_PREFIX,
                        reactor.netty.Metrics.URI,
                        100,
                        MeterFilter.deny()
                    )
                )
        }
```

**Comment by patpatpat123** [comment]
Thanks!
