### ISSUE TITLE
How to resolve http param?

### ISSUE THREAD

**Issue by panyox** [reactor/reactor-netty#1716]
here is my code
```java
    public static void main(String[] args) {
        HttpServer server = HttpServer.create()
                .port(8088)
                .wiretap(WIRETAP)
                .compress(COMPRESS)
                .route(routes -> routes.post("/hello",(req,res)->{
                    System.out.println("---test params---");
                    System.out.println(req.param("a"));
                    Map<String,String> pm = req.params();
                    System.out.println(pm);
                    return res.header(CONTENT_TYPE, TEXT_PLAIN).sendString(Mono.just("Hello world"));
                }));
        server.bindNow().onDispose().block();
    }
```
<img width="576" alt="WX20210705-235726@2x" src="https://user-images.githubusercontent.com/77569707/124497050-dfb2f600-ddec-11eb-8ca1-d6373aded70a.png">

the params is aways null, what should i do?

<img width="727" alt="WX20210705-235748@2x" src="https://user-images.githubusercontent.com/77569707/124497073-ed687b80-ddec-11eb-8bb3-92cdaa7da8cb.png">

**Comment by violetagg** [comment]
@panyox The params that are available with `HttpServerRequest` are those URI parameter captured via `{}` - i.e. `/test/{var}`. When you use `x-www-form-urlencoded` the params are provided via request body (you can check the wire logs). Reactor Netty does not parse the request body.

The javadoc for https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServerRequest.html#param-java.lang.CharSequence- describes that behaviour, unfortunately it is not mentioned in the other method https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServerRequest.html#params--

I'm gonna update the javadoc so that it is clear that those params are URI parameter captured via `{}`.

**Comment by panyox** [comment]
em... ok.
