### ISSUE TITLE
 How does reactor netty deal with cross domain problems?

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#1734]
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@1ssqq1lxr There isn't built-in support for that in Reactor Netty, but you can extend it with CORS handler provided by Netty

https://github.com/netty/netty/tree/4.1/codec-http/src/main/java/io/netty/handler/codec/http/cors

You can use `doOnConnection` callback in order to add that handler.
What do you think? Will this solve your use case?

**Comment by violetagg** [comment]
@1ssqq1lxr I'm closing this. If you have additional questions we can continue the discussion on [Gitter](https://gitter.im/reactor/reactor-netty)
