### ISSUE TITLE
PooledConnectionProvider leaks metrics

### ISSUE THREAD

**Issue by agaoglu** [reactor/reactor-netty#1809]
## Expected Behavior

PooledConnectionProvider to pool metrics too

## Actual Behavior

Leaking metrics and memory leading to OOME after some time. I think it generates a new metric for each connection attempt and does not drop an older one.

## Steps to Reproduce

Not really sure but my application is trying to pull live data from a few dozen sources, retrying connections when necessary. And some addresses may not be available for extended periods so it tries them every minute or so, increasing the memory and the number of metrics. The easiest way to confirm is to check the prometheus metrics output. It produces multiple labels for the same address like: 

```
reactor_netty_connection_provider_idle_connections{id="1972024777",name="tcp",remote_address="192.168.30.85:554",} 0.0
reactor_netty_connection_provider_idle_connections{id="939845888",name="tcp",remote_address="192.168.30.85:554",} 0.0
reactor_netty_connection_provider_idle_connections{id="1882846747",name="tcp",remote_address="192.168.30.85:554",} 0.0
reactor_netty_connection_provider_idle_connections{id="-570625018",name="tcp",remote_address="192.168.30.85:554",} 0.0
reactor_netty_connection_provider_idle_connections{id="-210368611",name="tcp",remote_address="192.168.30.85:554",} 0.0
```

heap dump analysis shows some hints around channelPools in PooledConnectionProvider 

## Your Environment

* Reactor version(s) used: 1.0.11-SNAPSHOT (reactor-netty-1.0.11-20210913.101212-37)
* Other relevant libraries versions (eg. `netty`, ...): spring boot 2.5.4 but reactor-netty bumped to snapshot
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`): ubuntu 18.04

Just noticed the latest 1.0.11 release. I'm trying it now but it's only one commit ahead and it doesn't seem related.

**Comment by violetagg** [comment]
@agaoglu Can you provide some reproducible example?

**Comment by agaoglu** [comment]
of course. i'll be out of town for a few days though. next week i hope.

**Comment by agaoglu** [comment]
pushed to https://github.com/agaoglu/reactor-netty-1809 

While trying to simplify, I noticed that the problem is triggered by wiretapping the connection. No problems without it.

**Comment by violetagg** [comment]
@agaoglu You are creating the `TcpClient` every time. We try to share as much as possible resources but some of them we cannot share (for example the non default `wiretap`, `doOnDisconnected` callback etc. - most probably you do not want to create these objects every time), this will lead to your observation that every `TcpClient` has it own connection pool. When a connection pool is created, not only the remote address is taken into consideration but also the `TcpClient` configuration especially when it concerns the connection. Our recommendation is always to have a shared configuration in order to reuse as much as possible resources i.e.

```
TcpClient shared = TcpClient.create()
                .metrics(true)
                .wiretap("wiretap", LogLevel.TRACE)
                .doOnDisconnected(dc -> {
                    logger.warn("Connection to {} lost", address);
                    if (reconnect) {
                        // try to reconnect after 1 second
                        Mono.delay(Duration.ofSeconds(1))
                                .doOnNext(aLong -> connect())
                                .subscribe();
                    }
                });

TcpClient client1 = shared.host(host1)
                .port(port1)

TcpClient client2 = shared.host(host2)
                .port(port2)
```

**Comment by agaoglu** [comment]
Thanks for the heads up, we'll reuse the configuration wherever we can. Still, is there a way to destroy a tcpclient and release its resources?

Also a bit unrelated but the id label for these metrics looks a bit arbitrary. Is there a way to read it or correlate it to something else?

**Comment by violetagg** [comment]
@agaoglu I added PR #1816 that will take into consideration the wiretap configuration.

> is there a way to destroy a tcpclient and release its resources?

When you connect to the remote peer you receive a `Connection`. In order to destroy this connection you have `Connection#dispose...` methods.

For the connection pool, as you use the global connection provider, I would recommend to utilise the functionality for eviction of idle connections and/or disposal of inactive connection pools. Take a look here for more information https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool (configurations: `disposeInactivePoolsInBackground` and `evictInBackground `)

> Also a bit unrelated but the id label for these metrics looks a bit arbitrary. Is there a way to read it or correlate it to something else?

the connection pool id is unique for every connection pool and is generated
