### ISSUE TITLE
what's recommand configuration about connection pool

### ISSUE THREAD

**Issue by sodaRyCN** [reactor/reactor-netty#1846]
ConnectionProvider have some configuration. but no docs  explain recommand configuration.

maxConnections have to be cpu core multiple? or set 100/1000 by empirical estimation?

what's the relationship  between maxIdleTime and maxLifeTime. e.x: one connection inactive time over maxIdleTime  and  total time less than maxLifeTime, the connection will close ?  what's about less than maxIdleTime  and over maxLifeTime。

how to connection will be processed if evictInBackground setted ?

which one  fifo or lifo  be recommand? what's criteria ?

**Comment by violetagg** [comment]
@sodaRyCN Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) (real time discussions) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
