### ISSUE TITLE
[Enhancement request] Support JSON structured logging with AdvancedByteBufFormat

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#1851]
Hello Reactor Netty Team,

I would like to just start an enhancement request, hopefully this is not a trouble and you can find the time to consider this in an upcoming release.

Currently, the class ```AdvancedByteBufFormat``` support those format:

```
SIMPLE
HEX_DUMP
TEXTUAL
```

Those format are already great, thanks for the work.
May I ask if it is also possible to **enable structured JSON** please?

When using log aggregation and log indexing tools such as Elastic Stack, Splunk, or Graylog, it is best practice to generate logs in a structured format, such as JSON.

The structured key-value format enables log collectors to efficiently ship the data to the back end log aggregator.

Finally, having JSON format as search result directly enable much more possibilities to build more advanced search queries.

Therefore, it will be great if team here can consider the enhancement to support such.

Thank you!

**Comment by ctlove0523** [comment]
@patpatpat123 
In current framework,i think this need [Netty](https://github.com/netty/netty) first support.

**Comment by ctlove0523** [comment]
@patpatpat123 yes

**Comment by patpatpat123** [comment]
Understood, let me see the about the forward from Simon as well, to see if there are any update on that front

**Comment by ctlove0523** [comment]
I think @patpatpat123 want reactor netty directly output json format log

**Comment by patpatpat123** [comment]
Thank you all for your time and consideration

**Comment by violetagg** [comment]
@patpatpat123 @ctlove0523 I started looking at this one.

Did you try to search for OSS projects that already provide this functionality?

This cannot be introduced as part of the wire logger functionality, because the current wire logger works only with `ByteBuf`. It is not possible to make a json with the various HTTP components.

This can be implemented either as a separate API or a separate Netty handler.

An OSS project with a Netty handler that provides similar functionality is https://github.com/zalando/logbook (there might be other OSS projects that provide the same. I just picked this and tried to integrated it with Reactor Netty)

You need just to configure the Netty handler like this

```
public static void main(String[] args) {
	Logbook logbook =
			Logbook.builder()
			       .sink(new DefaultSink(new JsonHttpLogFormatter(), new DefaultHttpLogWriter()))
			       .build();

	DisposableServer server =
			HttpServer.create()
			          .doOnConnection(connection -> connection.addHandler(new LogbookServerHandler(logbook)))
			          .handle((req, res) -> res.send(req.receive().retain()))
			          .bindNow();

	server.onDispose()
	      .block();
}
```

and then you will have the following output in the logs:

```
18:01:19.322 [reactor-http-nio-2] TRACE org.zalando.logbook.Logbook - {"origin":"remote","type":"request","correlation":"9f5fb4b623cbb06f","protocol":"HTTP/1.1","remote":"/127.0.0.1:52070","method":"POST","uri":"http://localhost:52062/","host":"localhost","path":"/","scheme":"http","port":"52062","headers":{"Accept":["*/*"],"content-length":["12"],"Content-Type":["application/x-www-form-urlencoded"],"Host":["localhost:52062"],"User-Agent":["..."]},"body":"Hello World!"}
...
18:01:19.329 [reactor-http-nio-2] TRACE org.zalando.logbook.Logbook - {"origin":"local","type":"response","correlation":"9f5fb4b623cbb06f","duration":82,"protocol":"HTTP/1.1","status":200,"headers":{"transfer-encoding":["chunked"]},"body":"Hello World!"}
```

I'm thinking about to reject this feature request as it appears that there are projects that provide the requested enhancement and the integration with Reactor Netty is easy.

**Comment by patpatpat123** [comment]
Hello @violetagg ,

Many thanks for looking into this.
What I was proposing as enhancement request, was a native support to convert to JSON, within netty, without having to incorporate yet another layer.

But your explanations are very clear, and this enchantment request is more of a good to close.

Thank you again for your time.
