### ISSUE TITLE
[inputs.statsd] Splitting '|', unable to parse- while publishing HttpClient metrics

### ISSUE THREAD

**Issue by rabiprof** [reactor/reactor-netty#1910]
In our project , we have enabled metrics for webclient, beow is the sample config
val webclient = Webclient.create().metrics(true,{
//tags
})

It is throwing below errors in the telegraf log:

"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientAddressResolve.remoteAddress.xyz.com:80.SUCCESS.p99:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientDateSent.remoteAddress.xyz.com:80.SUCCESS.p99:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientDateReceived.remoteAddress.xyz.com:80.SUCCESS.p99:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientConnectionTime.remoteAddress.xyz.com:80.SUCCESS.mean:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientDataReceivedTime.remoteAddress.xyz.com:80.SUCCESS.mean:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientDataSentTime.remoteAddress.xyz.com:80.SUCCESS.mean:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyHttpClientResponseTime.remoteAddress.xyz.com:80.SUCCESS.mean:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyConnectionProviderActiveConnections.id.1234.name.connectioinPool.xyz.com:80:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyConnectionProviderIdleConnections.id.1234.name.connectioinPool.xyz.com:80:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyConnectionProviderPendingConnections.id.1234.name.connectioinPool.xyz.com:80:406.43|g"
"[inputs.statsd] Splitting '|' unable to parse metrics : reactorNettyConnectionProviderTotalConnections.id.1234.name.connectioinPool.xyz.com:80:406.43|g"

## Expected Behavior
It should publish all the metrices without any error

## Actual Behavior
Partial metrics of weclient are getting published and above are failing 

## Steps to Reproduce
1) enable Webclient metrics in a test project and publish metrics through telegraf(using stasd) 
2) make any api call and monitor the telegraf log to observe the errors

##Analysis 
-> As per my analysis above metrices are falling because of  ":<port_number>" , due to colon(":" ) in the tag of address, telegraf is not able to parse the tag.
-> reactor.netty.hht.client.MicrometerHttpClientMetricsRecorder, MicrometerHttpMetricsRecorder and MicrometerChannelMetricsRecoder are using "reactor.netty.Metrics.formatSocketAddress(socketAdress)" to convert SocketAdress to string.
-> In Metrics.formatSocketAddress(socketAdress) method, we are returning "hostString":"port"(this string is causing the issue)

## Your Environment
Reactor version(s) used:
 reactor-core : 3.4.8
 reactor-netty:1.0.9
JVM version :11
 
## Possible Solution
-> In Metrics.formatSocketAddress(socketAdress) method remove colon(":") with Dot(".")

**Comment by shakuzen** [comment]
How are you configuring your `StatsdMeterRegistry`? If you are using the telegraf `flavor`, we are replacing `:` characters already. See [this line](https://github.com/micrometer-metrics/micrometer/blob/008d47999be9e4dea7eeae4916924175355d4655/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/TelegrafStatsdLineBuilder.java#L93) in `TelegrafStatsdLineBuilder`.

**Comment by violetagg** [comment]
@rabiprof I'm closing this one, if it appears an issue with Reactor Netty, we can reopen it.

**Comment by rabiprof** [comment]
@shakuzen we are using mix of Dropwizard and micrometer core , so we have a custom StatsdMeterRegistry and we are not using micrometer-registry-statsd lib

**Comment by shakuzen** [comment]
It sounds like you'll want to do something similar in your custom MeterRegistry implementation to what we do in micrometer-registry-statsd, then. Instrumentation (like `MicrometerHttpClientMetricsRecorder` here in reactor-netty) shouldn't need to know about all the constraints that might be imposed by different MeterRegistry implementations. I think it's therefore not necessary and not appropriate to change the instrumentation here.

**Comment by rabiprof** [comment]
@shakuzen Generally tags does not contain any special characters like( [ ] , : ; " | * & \ / ? $ £ ( ) { } ^ ~) , 
When someone is using any default Instrumentation to publish metrics they need to know all the special characters are getting used to build tags for their their custom MeterRegistry and this is not always backward compatible.

**Comment by shakuzen** [comment]
> When someone is using any default Instrumentation to publish metrics they need to know all the special characters, which are getting used to build tags for their their custom MeterRegistry and this is not always backward compatible.

Users of a `MeterRegistry` or libraries writing instrumentation don't need to care about sanitization because the `MeterRegistry` takes care of it for them. People developing `MeterRegistry` implementations need to care about this.

The change you proposed is not backwards compatible because it changes the tag value to something other than it's always been. This would affect everyone, even if there is no problem with the tag value in their metrics backend or the `MeterRegistry` implementation they use properly handles normalization and sanitization as necessary.

It is the responsibility of the `MeterRegistry` implementation to know what characters are allowed by its supported backend in meter names, tag names, and tag values.
It is not the responsibility of instrumentation to know about such things, because it can be different for each `MeterRegistry` and instrumentation does not know what `MeterRegistry` is configured by a user.

If the `MeterRegistry` you are using is not handling sanitization of meter names, tag names, and tag values as appropriate for its intended metrics backend, then that is a bug in the `MeterRegistry` implementation.

You don't need to know all the special characters used in instrumentation, you need to handle any special character that your metrics backend does not allow.
