### ISSUE TITLE
Netty .wireTap() exclude certain headers

### ISSUE THREAD

**Issue by mocanuMatei** [reactor/reactor-netty#2044]
Hi guys, 

I log the request body for every webClient request via Netty wiretap. But how can I exclude certain headers from logging? Some endpoints need Basic auth and therefor the plain passwords will be logged in production by Netty wiretap. 
Here is my HttpClient configuration:

HttpClient httpClient = HttpClient
      .create()
      .wiretap("reactor.netty.http.client.HttpClient",
               logLevel, AdvancedByteBufFormat.TEXTUAL)
      .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeoutMillis)
      .secure(t -> t.sslContext(sslContext))
      .doOnConnected(connection -> connection
        .addHandlerLast(new ReadTimeoutHandler(readTimeoutMillis)));

**Comment by violetagg** [comment]
@mocanuMatei `wiretap` functionality in Reactor Netty is protocol agnostic and we cannot provide any filtering for HTTP headers. Also we do not recommend enabling `wiretap` in production (especially logging the incoming/outgoing data that might be huge). 
You can provide your own `LoggingHandler` that handle your use case. You can add this handler using the same API as in the example above for `ReadTimeoutHandler`. As described in javadoc `Connection.addHandler*` methods guarantee that your handler will be added after the HTTP Codecs (for HttpClient) so that you will be able to access the HTTP request/response metadata and filter it.
https://projectreactor.io/docs/netty/release/api/reactor/netty/Connection.html#addHandler-io.netty.channel.ChannelHandler-
