### ISSUE TITLE
[Request For Documentation ] Handling request body in HttpServer is a little brief

### ISSUE THREAD

**Issue by xishian** [reactor/reactor-netty#2058]
## Motivation

https://projectreactor.io/docs/netty/release/reference/index.html#_consuming_data_3

The section of Consuming data is too short. For example, how can I throw an exception when the request body is empty?

Sorry, I search on google and stackoverflow many times, but nothing found, so I open an issue.

## Desired solution

Provide more detailed documentation or examples  about handing the request body, thanks.

## Additional context

How can I throw an exception when the request body is empty?

My code for handling request body:

```
           //if request body is empty, the method check() will not be invoked
           Mono<String> mono = request.receive()
                    .aggregate()
                    .asByteArray()
                    .flatMap(data -> Mono.just(check(info, data, request.requestId())));

            return response.status(HttpResponseStatus.OK)
                    .header(HttpHeaderNames.CONTENT_TYPE, "application/json")
                    .sendString(mono);
```

**Comment by pderop** [comment]
Hi @xishian,

You can do what you want using the _reactor-core_ API. Now _reactor-netty_ project is an extension of the _reactor-core_ API on top of netty, that's why we only provide informations related to reactor-netty API, and for general documentation regarding reactor-core, you can refer to the [reference documentation](https://projectreactor.io/docs/core/release/reference/index.html#getting).

Now, regarding your specific question, I think you can use the reactor-core _switchIfEmpty_ operator, which allows to handle cases when a Flux or a Mono source is empty (please check in particular this [section](https://projectreactor.io/docs/core/release/reference/index.html#_checking_the_execution_path_with_publisherprobe) from the reference documentation).

Taking your initial example, it would be something like this:

```
           Mono<String> mono = request.receive()
                    .aggregate()
                    .asByteArray()
                    .flatMap(data -> Mono.just(check(info, data, request.requestId())))
                    .switchIfEmpty(Mono.error(new IllegalArgumentException()));

            return response.status(HttpResponseStatus.OK)
                    .header(HttpHeaderNames.CONTENT_TYPE, "application/json")
                    .sendString(mono);
```

hope this helps.

**Comment by pderop** [comment]
I'm closing this one, feel free to reopen if needed.
