### ISSUE TITLE
Question on blocking retries (not an issue/bug)

### ISSUE THREAD

**Issue by ogorostis** [reactor/reactor-netty#2146]
Hi,
I just would like to understand better the rationale for blocking retries once some data has been sent at
https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L360
Is it simply : once some data has been sent (whether it be by body or by headers), who knows what the serving end has done, hence let's not retry because better safe than sorry ?
Thanks.
Olivier

**Comment by violetagg** [comment]
@ogorostis Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
