### ISSUE TITLE
Need information regarding TcpClient Connection Pool

### ISSUE THREAD

**Issue by Huthesh** [reactor/reactor-netty#2223]
I have a requirement where i need to connect 10000 different hosts concurrently. Here I just need to perform a TCP connection and disconnect. Not further communication will be done with remote host. I am using TCPClient.
My question is increasing the connection pool will it help the performance in any way?

What is the best way to achieve this using TCPclient without overloading CPU?

**Comment by violetagg** [comment]
@Huthesh Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
