### ISSUE TITLE
how can i add some childHandler in TcpServer ?

### ISSUE THREAD

**Issue by RexChengZhu** [reactor/reactor-netty#2251]
hello
i want to add some ChannelHandler in pipeline like Netty, but it's useless . what's wrong . the reactor-netty version is 0.9.7.RELEASE 
THX

```
  TcpServer.create()
           .port(8080)
           .bootstrap(bs->{
               return bs.childHandler(new ChannelInitializer<SocketChannel>() {
                   @Override
                   protected void initChannel(SocketChannel ch) throws Exception {
                       ch.pipeline().addLast(new ChannelInboundHandlerAdapter(){
                           @Override
                           public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                               super.channelRead(ctx, msg);
                           }
                       });
                   }
               });
           })
           .handle((res,resp)->{
               return resp.sendString(Mono.just("hello world"));
           }).bindNow()
           .onDispose()
           .block();
```

**Comment by violetagg** [comment]
@RexChengZhu Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

**Comment by violetagg** [comment]
@RexChengZhu I will recommend you to upgrade to Reactor Netty 1.0.x version as 0.9.x version is no longer supported!
