### ISSUE TITLE
[Question]  question on configuration IO_SELECT_COUNT

### ISSUE THREAD

**Issue by huangydyn** [reactor/reactor-netty#2254]
I'm using SpringCloudGateway, I have an doubt on config parameter `IO_SELECT_COUNT`
```
/**
 * Default selector thread count, fallback to -1 (no selector thread)
 */
public static final String IO_SELECT_COUNT = "reactor.netty.ioSelectCount";
```
Is this the thread count of netty boss reactor group? why could this be -1 by default?

And could you provide suggestion for the configuration of this parameter `IO_SELECT_COUNT`?

**Comment by violetagg** [comment]
@huangydyn Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

**Comment by violetagg** [comment]
https://stackoverflow.com/questions/72408107/springcloudgateway-configuration-parameter-io-select-count
