### ISSUE TITLE
Graceful shutdown for TcpServer.dispose()

### ISSUE THREAD

**Issue by flikas** [reactor/reactor-netty#2451]
When a ChannelGroup is provided, DisposableServer#disposeNow(Duration) will wait the active requests to finish. But dispose() will not.

## Motivation

It should be better that dispose() supports graceful shutdown, too.

**Comment by pderop** [comment]
hi @flikas ,

From my understanding, the _dispose()_ method is non-blocking, while the _disposeNow(Duration) method is. 

So, if a ChannelGroup is provided,  are you asking to change the _dispose()_ method in order to block until all active requests are done ? then wouldn't this be a very strong API  change, in terms of behavior ? I mean, the dispose() method would then become a blocking method, which is something we probably do not desire, since Disposable.dispose() method is  usually not blocking ?

now, if you need to gracefully shutdown a server without blocking, then wouldn't it be better to introduce a new "Mono<Void>  disposeLater(Duration)" method. It would allow to do a graceful shutdown without blocking, and subscribers would then be notified asynchrously when the shutdown is effective ?
WDYT ?

**Comment by flikas** [comment]
hi @pderop ,
I think `dispose()` should be non-blocking, too. A new `Mono disposeLater(Duration)` method is great.
I've used `onDispose()` to get a Mono to be notified asynchronously, and then `dispose()`, which is failed for graceful shutdown.

**Comment by pderop** [comment]
@flikas ,

By the way, can you clarify the use case you are trying to achieve ? Disposing the server in most cases means shutdown the jvm. So, are you disposing the server in some other use cases ?

thank you.

**Comment by violetagg** [comment]
@flikas ,
> 
> By the way, can you clarify the use case you are trying to achieve ? Disposing the server in most cases means shutdown the jvm. So, are you disposing the server in some other use cases ?
> 
> thank you.

Can you share with us your use case

**Comment by violetagg** [comment]
@flikas I'm closing this one. We can reopen it when you can provide the requested information.
