### ISSUE TITLE
increase maximum server sent connections

### ISSUE THREAD

**Issue by bhukailas** [reactor/reactor-netty#2479]
i was load testing server sent events a backend netty with spring boot web flux  server can have. what we see it is always 500.
is there a way to increase number of parllel server sent event connection can be supported by netty?

we already tried following already. But none of them are really helping us.

```
reactor.netty.connection.provider.max.connections=2000
reactor.netty.pool.maxConnections=2000
reactor.netty.connection.provider.total.connections=2000
reactor.netty.connection.provider.active.connections=2000
```

**Comment by violetagg** [comment]
@bhukailas Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
