### ISSUE TITLE
Memory leak with webclient timeout

### ISSUE THREAD

**Issue by nmadhavi33** [reactor/reactor-netty#2500]
webClient.post()
                .uri(url)
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON)
                .bodyValue(XXX)
                .retrieve()
                .bodyToMono(XXX.class)
                .timeout(Duration.ofMillis(10000))
                .doOnError(TimeoutException.class){
log.error("time out exception")
                }

I see memory leak when timeout exception happens. Can you please suggest how to handle timeout exception with fall back option

**Comment by pderop** [comment]
Ii @nmadhavi33,

It is recommended to use the  [reactor-netty timer configuration](https://projectreactor.io/docs/netty/release/reference/index.html#_timeout_configuration) in order to enable request timeout, and to handle timeout fallback, you can refer to the [reactor core documentation](https://projectreactor.io/docs/core/release/reference/index.html), there are multiple ways to do do (check "Example of Reactor code with timeout and fallback" for one of the many examples).

For example, in the sample code below, I'm using _onErrorResume_ (but the exception type should be checked, not done in the example below):

```
        HttpClient client = HttpClient.create()
                .responseTimeout(Duration.ofMillis(1));

        WebClient webClient = WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(client.metrics(true, Function.identity()).protocol(protocol)))
                .baseUrl(URL).build();

        Flux.range(1, 100000000)
                .publishOn(Schedulers.boundedElastic())
                .flatMap(integer -> webClient
                                .get()
                                .retrieve()
                                .bodyToMono(String.class)
                                .onErrorResume(e -> {
                                    return Mono.just("failback response"); })
                        , 256)
                .subscribe(s -> {...}, err -> err.printStackTrace());
    }
```

I'm currently running a load test using the above code, but the memory seems stable.
I also did a test using the Mono.timeout() instead of using reactor netty responseTimeout, and the memory seems to also remain stable.


So, can you please provide the following:

- a minimal reproducer project that is loading a server using the web client project (no need to include a server)
- what is the protocol used ? HTTP ? HTTPS ? H2 ?
- what are the versions used for reactor-netty and the web client ?
- what is the jdk version used

thanks.

**Comment by nmadhavi33** [comment]
Hi @pderop , thanks for your response 

I see issue with **TimeoutException** and not WebClientResponseException

exception stacktrace is below java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMapMany' **(and no fallback has been configured**)

how to configure fall back for  **java.util.concurrent.TimeoutException**

when **WebClientResponseException** was thrown, I do not see that error message with ' **(and no fallback has been configured**)

 webClient.post()
.uri(url)
.contentType(MediaType.APPLICATION_JSON)
.accept(MediaType.APPLICATION_JSON)
.bodyValue(XXX)
.retrieve()
.bodyToMono(XXX.class)
.timeout(Duration.ofMillis(10000))
**.doOnError(TimeoutException.class){**
log.error("time out exception")
return Mono.error(new RuntimeException("xyz");
}
**.doOnError(WebClientResponseException.class){****

  log.error("webclient exception")
  return Mono.error(new RuntimeException("abc");
}

**Comment by pderop** [comment]
If you are using Mono.timeout, so, you can do for example: 
```
webClient
    .get()
    .retrieve()
    .bodyToMono(String.class)
    .timeout(Duration.ofMillis(10))
    .onErrorResume(TimeoutException.class, timeout -> 
        Mono.just("failback response after request timeout")));
```

but again, we recommend to use the **responseTimeout** reactor netty timer configuration instead of the Mono.timeout, and you can also do the same in order to return a fallback value on request timeout. In this case, you need to use onErrorResume on the WebClientRequestException.class which will wrap the timeout exception thrown by netty (which is io.netty.handler.timeout.ReadTimeoutException).

something like:

```
HttpClient client = HttpClient.create()
    .responseTimeout(Duration.ofMillis(5));

webClient
    .get()
    .retrieve()
    .bodyToMono(String.class)
    .onErrorResume(WebClientRequestException.class, exception -> {
        if (exception.getCause() instanceof io.netty.handler.timeout.ReadTimeoutException) {
            return Mono.just("failback response after request timeout");
         } else {
            return Mono.just("failback response for other kind of exception ...");
        }
    });
```

**Comment by violetagg** [comment]
@nmadhavi33 Were you able to test @pderop suggestions?

**Comment by nmadhavi33** [comment]
@violetagg , 

I was able to test suggestions given by @pderop . Thank you, for your help.
