### ISSUE TITLE
 How can we disable HttpTrace method in reactory netty Http Server

### ISSUE THREAD

**Issue by Vamsi-Messi** [reactor/reactor-netty#2553]
Hi Team, iam using spring webflux for my application., which defaults to react netty http server.. so for security purposes i need to disable the http trace method., i tried many ways but couldn't found the soultion.. can suggest here pls.. thanks in advance..

**Comment by violetagg** [comment]
@Vamsi-Messi Spring WebFlux uses I/O Handler functionality that Reactor Netty provides. This means that Reactor Netty forwards to Spring WebFlux the request as is without any interpretation. Please contact Spring maintainers.

**Comment by Vamsi-Messi** [comment]
Hi @violetagg ., thanks for answer., as you mentioned i tried with spring provided classes .,

@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> httpServer.wiretap(true));
    }
here i need to tell to the httpServer(reactor) to not allow Trace requests to it. actually i didn't found any relevant method here.. please suggest.. thanks in advance

**Comment by violetagg** [comment]
@Vamsi-Messi That is not how things work.

Reactor Netty HTTP server has I/O handler and routing. One can use one of them in order to return a response.
* With routing by default you do not have `tracing` functionality and if you want to do something around tracing you have to provide your own routing implementation. See more in the reference documentation https://projectreactor.io/docs/netty/release/reference/index.html#_routing_http
* With I/O handler, the one that provides the I/O handler decides what to do, and Spring WebFlux uses this API. See more about I/O handlers https://projectreactor.io/docs/netty/release/reference/index.html#_writing_data_3

However if there is no configuration/API from Spring Framework, you can try to implement you own custom Netty handler and to intercept the whole chain. Something like this https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks_3
