### ISSUE TITLE
Uneven HTTP/2 connection to event loop distribution

### ISSUE THREAD

**Issue by samueldlightfoot** [reactor/reactor-netty#2604]
During profiling of Http2Pool I regularly saw a small fraction of webclient threads becoming very hot and processing the majority of the requests, whilst leaving other threads under-utilised.

For example, the below shows one thread (one event loop) doing more than 5 times the work of any other event loop. On investigation this appears to be down to new H2 connections being opened on the 'caller' event loop, rather than round-robin the connections to event loops, which is what the TransportConnector will do if no event loop is provided to 'connect' method.

Note in the below image 16 worker threads were set, which would create an EventLoopGroup with 16 EventLoops.

<img src="https://user-images.githubusercontent.com/84812011/206239778-06e1920b-72bc-431b-86fd-2d44869ac4f1.png" width="351" height="142">

Note I used a separate client event loop to server loop.

OS: Windows 10, 64-bit

## Expected Behavior

Connections should be distributed evenly across event loops (worker threads) in the event loop group.

## Actual Behavior

Large number of new connections opened assigned to same event loop,

## Steps to Reproduce

Checkout below repository, which contains 3 services and run.

Note I had SSL configured, so it is recommended to run with local keystore and cert.

https://github.com/samueldlightfoot/http2-distribution

1. Load gen
2. Client
3. Server

Hit load generator endpoint to trigger processing (Load Gen -> Client -> Server) using H2.

curl -X GET http://localhost:9000/call/{request-count}/{concurrency}

e.g. curl -X GET http://localhost:9000/call/50000/250

I found the problem gets worse at a higher concurrency factor, most likely due to need for more connections to handle load. So would recommend using 250+.

## Possible Solution

The caller event loop should not be used when opening new connections when a separate client event loop is provided to the  HttpClient. It should instead let the EventLoopGroup _Chooser_ do the selection of the next loop to use. I believe the intention of this 'caller loop' feature was for when client and server event loop is shared, which in this case, it is not.

The troublesome code seems to be in PooledConnectionProvider, where we grab event loop group, which is of type ColocatedEventLoopGroup, therefore we grab the thread local loop via nextInternal. _DefaultLoopResources_  cache*ClientLoops() always colocates client with server loop, hence this will always be a ColocatedEventLoopGroup. I can't quite get my head around if this is the intended behaviour.

```				
EventLoopGroup group = config.loopResources().onClient(config.isPreferNative());
if (group instanceof ColocatedEventLoopGroup) {
	eventLoop = ((ColocatedEventLoopGroup) group).nextInternal();
}
```

and then set into Reactor Context

```			
Mono<PooledRef<T>> mono = pool.acquire(Duration.ofMillis(poolFactory.pendingAcquireTimeout));
if (eventLoop != null) {
	mono = mono.contextWrite(ctx -> ctx.put(CONTEXT_CALLER_EVENTLOOP, eventLoop));
}
```

which then calls TransportConnector::connect with the loop from the Context

```
Publisher<PooledConnection> connectChannel() {
	return Mono.create(sink -> {
			PooledConnectionInitializer initializer = new PooledConnectionInitializer(sink);
		EventLoop callerEventLoop = sink.contextView().hasKey(CONTEXT_CALLER_EVENTLOOP) ?
				sink.contextView().get(CONTEXT_CALLER_EVENTLOOP) : null;
		if (callerEventLoop != null) {
			TransportConnector.connect(config, remoteAddress, resolver, initializer, callerEventLoop, sink.contextView())
					.subscribe(initializer);
		}
		else {
			TransportConnector.connect(config, remoteAddress, resolver, initializer, sink.contextView()).subscribe(initializer);
		}
	});
}
```

## Things I've Tried

As a test I overrode DefaultLoopResources::cacheNioClientLoops to use the NioEventLoopGroup directly rather than a ColocatedEventLoopGroup, and the distribution of connections was much better.

```
EventLoopGroup cacheNioClientLoops() {
	EventLoopGroup eventLoopGroup = clientLoops.get();
	if (null == eventLoopGroup) {
                // Below line was modified
		EventLoopGroup newEventLoopGroup = cacheNioServerLoops();
		if (!clientLoops.compareAndSet(null, newEventLoopGroup)) {
			// Do not shutdown newEventLoopGroup as this will shutdown the server loops
		}
		eventLoopGroup = cacheNioClientLoops();
	}
	return eventLoopGroup;
}
```

<img src="https://user-images.githubusercontent.com/84812011/206569712-ff1a241e-e99f-474a-b56c-d6ae49d28e55.png" width="351" height="268">

## Your Environment

* Reactor version(s) used: 1.1.0
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): JDK17
* OS and version (eg. `uname -a`): Windows 10

**Comment by samueldlightfoot** [comment]
@pderop Added details at the end with a quick test I did overriding DefaultLoopResources::cacheNioClientLoops.

**Comment by pderop** [comment]
I hope to start working on your issue tomorrow if I can.
thanks !

**Comment by pderop** [comment]
Hi @samueldlightfoot ,

The PR #2655 has been pushed in 1.0.x branch using commit https://github.com/reactor/reactor-netty/commit/d7f96213bdcadbd07f66f4b056e2b0406ce75e8e, which has been merged into main branch using commit https://github.com/reactor/reactor-netty/commit/cfb4996e76eb5a982f25079cff6ca6e595d2eeb8, and merged into netty5 branch using commit https://github.com/reactor/reactor-netty/commit/68322034670b720ae697557ebe874f051524fef9

Please read #2655 for the details.

In the DefaultLoopResources, we did not disable colocation, because it is needed in some scenario.
So, what we have done is that we have introduced a new [LoopResources.create](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java#L149-L176) method signature which is taking as last argument a 'colocate' flag. Please update your reproducer scenario like this: in the [HttpClientConfig](https://github.com/samueldlightfoot/http2-distribution/blob/master/client/src/main/java/client/HttpClientConfig.java#L31), replace:

```
.runOn(LoopResources.create("client", 16, true)) 
```

by:

```
.runOn(LoopResources.create("client", -1, 16, true, false)
```

This will ensure that when the Http2Pool tries to acquire more connections from one of the "client" custom eventloop group, then it will pick up new channels in a round-robin way, instead of reusing the current custom event loop. I tested in my environment, and I know see that all custom "client" event loops are almost evenly distributed among client channels.

Please reopen this issue if you are not satisfied, let me know;

thanks.

**Comment by samueldlightfoot** [comment]
Thank you @pderop, this is perfect. Great work.
