### ISSUE TITLE
I want to print the netty request log and error log. What should I do

### ISSUE THREAD

**Issue by ysl19910806** [reactor/reactor-netty#2639]
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@ysl19910806 Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
