### ISSUE TITLE
AbortCanceled Exception Handling

### ISSUE THREAD

**Issue by valoricDe** [reactor/reactor-netty#2674]
Hello Folks, sry to misuse this issue tracker but could someone support or guide me which project (spring/netty/reactor/coRouter) is probably the right one to approach?

https://stackoverflow.com/questions/75224316/handling-netty-abortedexception-in-spring-boot-corouter-application

**Comment by violetagg** [comment]
@valoricDe 

I created one simple application demonstrating that with plain java you can handle this exception

https://github.com/violetagg/GH-2674

- Run `DemoApplication` - this will start the server
- Run `ClientApplication` - this will send one request and then will close the connection in order to trigger `AbortedException`

You will be able to see that the `Controller` on the server can handle this exception. 

I cannot comment about `coRouter`

**Comment by valoricDe** [comment]
Thank you! That helps a ton to nail the problem down.
