### ISSUE TITLE
Limit lifetime of HTTP server persistent connections for HTTP2

### ISSUE THREAD

**Issue by AkashKumarAM21** [reactor/reactor-netty#2769]
From https://github.com/reactor/reactor-netty/issues/1865, We have maxKeepAliveRequests to support max request that a connection can handle for HTTP1.1. Requesting same feature for HTTP2.

**Comment by violetagg** [comment]
@AkashKumarAM21 Can you be more specific about this feature?
With HTTP/2 we have streams within a connection.
So this request is:
- After reaching `n` number of streams to close the connection
- OR limit the connection to handle up to `n` number of streams in parallel

**Comment by jattisha** [comment]
Hi Violeta,

We're looking for the first option, After reaching `n` number of streams to close the connection. I believe that the second option you suggested is already offered as the [`maxConcurrentStreams`](https://netty.io/4.1/api/io/netty/handler/codec/http2/Http2Settings.html#maxConcurrentStreams-long-) setting (unless I'm mistaken on what this feature does?). We did try to use that to resolve our issue, but it proved to not help enough for what we are looking for.

For more context, we are in a scenario where we have many host instances sitting behind a load balancer, and the end user connects directly to one of the instances over H2. In this scenario, we have a risk where a user can send a LOT of requests in a very short period of time and eat up the entire host's capacity. We did try limiting the number of concurrent streams, but after trying this, it didn't really solve our issue, since the requests were being fulfilled fast enough that we still got hit with a ton of requests. Limiting concurrent streams doesn't exactly mitigate our risk, since there's still the likelihood that a few users can connect to the same host and do the same thing.

The desire with this feature request is that we would be able to close a connection after a given number of requests (say, 100), at which point the connection would be closed and the client would open up a new connection to a possibly different host and distribute the load across our entire fleet instead of focusing the load on a single host and browning it out. This would ideally be used in tandem with `maxConcurrentStreams` to provide more load-balancing when over H2.

**Comment by violetagg** [comment]
@jattisha For which version do you need these configurations? 1.0.x or 1.1.x?

**Comment by jattisha** [comment]
We are using 1.0.x today, but I think we could move to 1.1.x if need be.

**Comment by jattisha** [comment]
Awesome, thanks @violetagg for the quick fix!

**Comment by violetagg** [comment]
@AkashKumarAM21 @jattisha It will be great if you can test the 1.0.33-SNAPSHOT version
