### ISSUE TITLE
Missing Trace and Span ID when using channel handlers on a HttpClient

### ISSUE THREAD

**Issue by mskomrak** [reactor/reactor-netty#2774]
See [Gitter thread](https://app.gitter.im/#/room/#reactor_reactor-netty:gitter.im/$gerUhUfvhzYKni-DtIjzNAv4JeZhv2vR_vHMST3MulI) for context.

Original issue relates to adding trace and span IDs in the `HttpClient` wiretap logs. This can be resolved with the solution suggested in the thread - by adding `TracingChannelOutboundHandler` and `TracingChannelInboundHandler` as provided.
However adding a `AdvancedByteBufFormat#toLoggingHandler` (or a [LogbookClientHandler](https://github.com/zalando/logbook/blob/main/logbook-netty/src/main/java/org/zalando/logbook/netty/LogbookClientHandler.java)) results in unexpected behavior - see https://github.com/mskomrak/boot-tracing-reactor-netty-sample/blob/3d24d010fc4186418951d4ba92b068463a0d8603/README.md

## Expected Behavior
Consistent output of logs including MDC data - e.g. logging handlers outputting logs with trace and span ID included (for all events) and no missing logbook statements.

## Actual Behavior
See readme above.

## Steps to Reproduce
See [reproducer](https://github.com/mskomrak/boot-tracing-reactor-netty-sample).

## Your Environment

* Reactor version(s) used: 3.5.4
* Other relevant libraries versions: reactor-netty 1.1.5
* JVM version (`java -version`)
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 19.0.2+7-jvmci-22.3-b12)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 19.0.2+7-jvmci-22.3-b12, mixed mode, sharing)
```
* OS and version (eg. `uname -a`): `Linux jupiter 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pderop** [comment]
Hi @mskomrak ,

I have given a try to the reproducer.
So, for the second request, indeed, I see that the logs for the `org.zalando.logbook.Logbook` logger are missing, but it seems that I see all traceIds for the `reactor.netty.http.client.HttpClient` log.

this is strange.

Now, after some research, I found this old logbook [issue 884](https://github.com/zalando/logbook/issues/884) which is still opened, and which seems similar to your problem. 
So, I have cloned the logbook version 3.0.0-RC.0, and have applied and rebuilt the patch from the corresponding [PR](https://github.com/PraneshSoma/logbook/pull/2/files) for the logbook 884 issue.
Then I have modified your reproducer in order to use mavenLocal(), and this time, it seems that the second requests includes the logs for the `org.zalando.logbook.Logbook` logger.

I have attached the [ko.log](https://github.com/reactor/reactor-netty/files/11253445/ko.log) without the patch, and [ok.log](https://github.com/reactor/reactor-netty/files/11253446/ok.log) with the patch applied to logbook.

So, can you do the same than me and confirm that it partially resolves at least the issue where you don't see the `org.zalando.logbook.Logbook` logger for the second request ?

**Comment by mskomrak** [comment]
@pderop thanks for the feedback and pointing out the logbook issue. I'l try to recheck in the next few days if I can reproduce the reactor-netty specific issue get back to you.

**Comment by pderop** [comment]
Hi @mskomrak ,

I'm closing this one for the moment; of course, if you have any updates, then we can reopen this issue.
thanks !
