### ISSUE TITLE
Queries regarding the congestion control mechanism used in the Netty server for incoming requests

### ISSUE THREAD

**Issue by owaiscs001** [reactor/reactor-netty#2803]
Hi Team

I have questions regarding the congestion control mechanism of the Netty server for incoming requests:

Q1: Is there any document on how queues are used in the Netty server, is it per http2 connection?
Q2: Is there a way to set the queue size, so that in case of overload excess packets are discarded?
Q3: Is there any metric to monitor these queue sizes? 
Q4: Is there any document that explains how congestion control is implemented in the reactor Netty server?

We are trying to implement overload control mechanism in our application that uses reactor Netty, Hence wanted to understand whether Netty offers any congestion control mechanism.

Thanks in advance.

**Comment by violetagg** [comment]
@owaiscs001 Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by owaiscs001** [comment]
@violetagg I have re-posted the question on [Stack Overflow](https://stackoverflow.com/questions/76242863/queries-regarding-the-congestion-control-mechanism-used-in-the-reactor-netty-for) and [Gitter](https://matrix.to/#/!rdZMIWMDXqzVEagqCt:gitter.im/$flokzdv-Ck1YzyJ3SMHSW6nrq6Pwo26IEdZD9OxKfD4?via=gitter.im). 
 Thanks

**Comment by owaiscs001** [comment]
Hi @violetagg 

I didn't receive any response on Stack Overflow/Gitter, can you please provide some help here or on the above links? I don't know how to set queue size for congestions control of incoming http2 requestion. Also wanted to know if there is any documentation on reactor netty congestion control. Further, I want to know if there is any monitoring mechanism for congestion control of incoming requests. My application is crashing with high traffic without any knowledge of reactor netty congestion control I’m unable to proceed further.

Thanks
