### ISSUE TITLE
UDP connections stay open with HttpClient.newConnection().resolver(spec -> {}) 

### ISSUE THREAD

**Issue by fzilic** [reactor/reactor-netty#2878]
When customizing resolver for HttpClient UDP connections stay open and can lead to resource starvation.

## Expected Behavior
UDP connections should not be left hanging after client completion.

## Actual Behavior
After each client completion UDP connection is left hanging, noticed problem in a docker environment, replicated on bare-metal Linux.

## Steps to Reproduce
```java
    @Test
    void releasesDnsConnections() {
        Mono.defer(() ->
                        HttpClient.newConnection()
                                .host("anyhost.example.org")
                                .port(80)
                                .baseUrl("/")
                                .get()
                                .response())
                .repeat(100)
                .blockLast();
        // pause execution here and verify number of open UDP connections
        // netstat -anpu | grep java 
        // only one UDP connection 
    }

    @Test
    void shouldLeakDnsConnections() {
        Mono.defer(() ->
                        HttpClient.newConnection()
                                .resolver(nameResolverSpec -> {
                                })
                                .host("anyhost.example.org")
                                .port(80)
                                .baseUrl("/")
                                .get()
                                .response())
                .repeat(100)
                .blockLast();
        // pause execution here and verify number of open UDP connections
        // netstat -anpu | grep java
        // > 100 UDP connections
    }
```

## Your Environment
* Reactor version(s) used: 
  * io.projectreactor.netty:reactor-netty-http:1.0.30
  * io.projectreactor.netty:reactor-netty-http:1.0.35
  * io.projectreactor.netty:reactor-netty-http:1.1.10
* Other relevant libraries versions (eg. `netty`, ...): none - isolated project with only netty libraries included by reactor
* JVM version (`java -version`): 
  * `OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)`
* OS and version (eg. `uname -a`): 
  * `Linux XXXXX 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux`

**Comment by pderop** [comment]
Hello @fzilic ,

if I'm correct, by default, the HttpClient uses the default resolver that is shared by all HttpClient, that is why you do not observe any leaks when running the `releasesDnsConnections` test. All HttpClient will reuse the same AddressResolverGroup obtained from [here](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java#L161).

Now, in `shouldLeakDnsConnections`, this is different: for each http request, this test creates a full HttpClient instance, and each HttpClient is configured with a specific resolver configuration using `resolver(spec -> ...`. 

Now, the `resolver` method actually creates a new  DnsAddressResolverGroup instance for each HttpClient created, see [here](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java#L338).

If you need to use a custom Dns resolver, I think that you need to create a single HttpClient and share it for all your HttpRequests (and it is actually recommended to share a single HttpClient for all your requests in order to avoid creating too much resources). Then the leak won't happen anymore.

Please modify the `shouldLeakDnsConnections` like this, and you won't see dns leaking anymore:

```
	@Test
	void shouldNotLeakDnsConnections() throws InterruptedException {
		HttpClient client = HttpClient.newConnection()
				.resolver(spec -> spec.queryTimeout(Duration.ofMillis(500)));

		Mono.defer(() ->
						client
								.host("www.yahoo.fr")
								.port(80)
								.baseUrl("/")
								.get()
								.response())
				.repeat(100)
				.blockLast();
		// pause execution here and verify number of open UDP connections
		// netstat -anpu | grep java
		// > 100 UDP connections

		Thread.sleep(Integer.MAX_VALUE);
	}
```

I'm closing this issue for the moment, feel free to reopen it if this is necessary.

thanks.
