### ISSUE TITLE
java problem

### ISSUE THREAD

**Issue by successpp** [reactor/reactor-netty#2908]
I have a problem. I may need your help. In springboot, I use thread local to store logs for each request, but I use a thread pool and the logs printed in the thread pool are not stored in the main thread. Is there any solution

**Comment by violetagg** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
