### ISSUE TITLE
Netty HttpClient - Capture / Log time taken for resolving DNS

### ISSUE THREAD

**Issue by syedyusufh** [reactor/reactor-netty#3368]
We are seeing a delay in `Spring WebClient` calls at times in our container application and are suspecting the DNS resolution. What would be the best way to capture the time taken for DNS resolution? Should it be done manually by customizing the `Netty HttpClient` as below or can it be achieved enabling logging level on `Netty` transport?

```
HttpClient.create()
          .doOnResolve()
          .doAfterResolve();
```

**Comment by violetagg** [comment]
@syedyusufh Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty) or [Stack Overflow](https://stackoverflow.com/questions/tagged/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.


And the answer to your question - Yes you can use these callbacks, we also provide metrics and tracing. Please review the documentation:
https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks_4
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_6
https://projectreactor.io/docs/netty/release/reference/index.html#_tracing_4
