### ISSUE TITLE
HTTP/2 connection stalls with APPLICATION_NDJSON

### ISSUE THREAD

**Issue by samueldlightfoot** [reactor/reactor-netty#3495]
**Summary**

When using HTTP/2 with APPLICATION_NDJSON, infinite connection hangs occur for endpoint calls when the input cardinality to a reactive stream reaches a certain size. The hangs seem to result from not consuming the data quickly enough, as removing concurrency limits on data consumption alleviates the issue.

The minimum reproducible example, as explained in the linked GitHub repository, involves more than a simple A-calls-B scenario. Specifically:

```A calls B (c1) and calls B again (c2) using the output produced from c1```

**Points of Interest**

- Hangs do not occur when using APPLICATION_JSON or HTTP/1.1.
- If a timeout handler is specified, it will eventually close the connection.
- Increasing the concurrency level at which data is consumed to a sufficient value prevents the hangs, perhaps indicating there is a consumption deadlock whereby two resources are waiting for a condition on each other.
- Using separate WebClient instances for c1 and c2 has no effect

**Steps to Reproduce**

To reproduce the issue, follow the steps provided in the minimal reproducible sample: https://github.com/samueldlightfoot/htt2-hangs/tree/main

Logs and further information is at the above GitHub link in the README.

Tested on Reactor Netty v1.1.23.

**Comment by samueldlightfoot** [comment]
Hi @chemicL,

Thank you for the excellent analysis—it’s fascinating to observe an example of HOL blocking in a real-world scenario.

Regarding the proposed solutions, all of which make sense: our priority is to maintain iterative data stream processing while avoiding unbounded buffering (i.e. collectList()). Increasing the initialWindowSize would provide a better safety margin, but it still leaves us vulnerable to the same issue with large incoming streams (e.g., GET requests) causing stalling. Similarly, increasing the connection count within the pool could reduce the likelihood but doesn’t fully address the root cause.

We will evaluate the feasibility of adopting HTTP/3, but do you see any other approaches that could completely eliminate the potential for HOL blocking, whilst using HTTP/2? I'm sure it must be something others have solved/struggled.

Thanks again.

**Comment by chemicL** [comment]
With **Option C** you'd be able to configure individual stream's window size for flow control. So you'd be able to reserve one stream for the initial GET request of size 32k and another stream of 32k for the data you expect as a result of the POST request. In such a case you'd not get into the stalling - the initial window will be applied per the entire connection while the individual streams' windows will be limiting the buffered data in transit up to the stream limit, still allowing another stream to use its limits. Worth experimenting as long as you can predict the amount of streams and how they interact.

Logically though, I think an **Option D** is worth mentioning. Since you are forming a pipe of `source -> sink` and because `sink == source` you get into an issue of forming a cycle reusing the connection for different concerns, perhaps it would be worth treating the POST path as a logically separate unit from the GET path and simply use a different `WebClient` instance for each? Such a configuration would also sound more flexible in case you at some point want to switch from using `sink == source` into a different model. Also in case of client side load balancing this problem might sometimes occur and sometimes not, so this would further prevent such non-deterministic failures.

With the above, I think we can close the issue as we don't anticipate any changes to reactor-netty codebase to address this as it is a specific use case and can be overcome via architectural decisions or customizations.

**Comment by samueldlightfoot** [comment]
@violetagg @chemicL I have done a small write-up up of the issue if you'd like to take a look. I thought it was interesting!

https://lightfoot.dev/http-2-flow-control-deadlock/
