### ISSUE TITLE
How to implement the classic Echo client-server?

### ISSUE THREAD

**Issue by asarkar** [reactor/reactor-netty#375]
I'm trying to implement an Echo client-server. I want the client to send some strings, finishing with "bye", and then shutdown. On receipt of "bye", the server would shutdown too.
This is surprisingly turning out to be not easy. The complete lack of documentation is mostly to blame, as well as my inexperience with reactor-netty. I understand well how to do this in Netty, but not clear about how to translate that to reactor API.

Following is my code in Kotlin:
```
class EchoServer(private val host: String, private val port: Int) {
    fun start() {
        val server = TcpServer.create(host, port)
        val handler = BiFunction<NettyInbound, NettyOutbound, Publisher<Void>> { inbound, outbound ->
            inbound.receive()
                    .asString(StandardCharsets.UTF_8)
                    .doOnNext {
                        LOGGER.info("Server received: {}.", it)
                        if (it == "bye") {
                            LOGGER.info("Stopping server.", it)
                            inbound.context().dispose()
                            outbound.context().dispose()
                        }
                    }
                    .doOnError { LOGGER.error(it.message, it) }
                    .flatMap {
                        outbound.sendString(Mono.just(it))
                                .neverComplete()
                    }
        }
        server.startAndAwait(handler)
    }

    companion object {
        val LOGGER = loggerFor<EchoServer>()

        @Throws(Exception::class)
        @JvmStatic
        fun main(args: Array<String>) {
            val host = args.getOrElse(0) { "localhost" }
            val port = args.getOrElse(1) { "8080" }.toInt()

            EchoServer(host, port).start()
        }
    }
}
```
```
class EchoClient(private val host: String, private val port: Int) {
    fun start() {
        val client = TcpClient.create(host, port)
        val handler = BiFunction<NettyInbound, NettyOutbound, Publisher<Void>> { inbound, outbound ->
            inbound.receive()
                    .asString(StandardCharsets.UTF_8)
                    .doOnNext {
                        LOGGER.info("Client received: {}.", it)
                        if (it == "bye") {
                            LOGGER.info("Stopping client.", it)
                            inbound.context().dispose()
                            outbound.context().dispose()
                        }
                    }
                    .doOnError { LOGGER.error(it.message, it) }

            outbound.sendString(Flux.fromArray(arrayOf("hi", "hello", "netty", "bye")))
                    .neverComplete()
        }
        client.startAndAwait(handler)
    }

    companion object {
        val LOGGER = loggerFor<EchoClient>()

        @Throws(Exception::class)
        @JvmStatic
        fun main(args: Array<String>) {
            val host = args.getOrElse(0) { "localhost" }
            val port = args.getOrElse(1) { "8080" }.toInt()
            EchoClient(host, port).start()
        }
    }
}
```

There are 2 problems with the above code:
1. The client is sending all the strings as one, not each one individually.
2. `context().dispose()` doesn't stop the server. I think I need a `shutdown`, but not clear how to invoke that depending on the input string.

**Comment by violetagg** [comment]
Hi,

1.
Let me start with flush operation:
When you need to flush after every message you need to specify the so called `send option` i.e. `outbound.options {t -> t.flushOnEach()}`
There are two variant of `flushOnEach`:
- By default we schedule the flush operation this means that with one flush operation we will flush as much as possible messages. This is done for optimisation as the flush operation might be expensive.
- You can explicitly specify the flush operation to be invoked after every message and this can be done with `flushOnEach(false)` which means do the flush immediately and do not schedule it.

However invoking `flush()` just instructs Netty to do the flush, but it also does an optimisation of the buffers and flushes so if the writes are small and fast you will again receive one combined message on the server side. In order to achieve one message and then flush you need to slow a bit the sending operation `Flux.fromArray(arrayOf("hi", "hello", "netty", "bye"))
                            .delayElements(Duration.ofMillis(100))`.

2.
There is a problem in your example on the client side. You instruct the client what to do when it receives the answer from the server, but actually you do not subscribe. You need to subscribe to the defined sequence in order to start receiving messages from the server.

3.
There is still one thing that I cannot understand. You dispose the inbound and outbound on both sides - server and client. What exactly you want to achieve:
- when the server receives `bye` to dispose OR
- when the client receives `bye` to dispose

If you dispose on the server when you receive `bye` then some messages might still not be sent to the client so you will miss them.

4. I reworked your example to the one below and I can see in the logs the scenario that you want (or the one that I think you want):

```
class EchoServer(private val host: String, private val port: Int) {
    fun start() {
        val server = TcpServer.create(host, port)
        val handler = BiFunction<NettyInbound, NettyOutbound, Publisher<Void>> { inbound, outbound ->
            inbound.receive()
                    .asString(StandardCharsets.UTF_8)
                    .doOnNext {
                        LOGGER.info("Server received: {}.", it)
                        //if (it == "bye") {
                        //    LOGGER.info("Stopping server.", it)
                        //    inbound.context().dispose()
                        //    outbound.context().dispose()
                        //}
                    }
                    .doOnError { LOGGER.error(it.message, it) }
                    .flatMap {
                        outbound.options {t -> t.flushOnEach(false)}
                                .sendString(Mono.just(it))
                                .neverComplete()
                    }
        }
        server.startAndAwait(handler)
    }

    companion object {
        val LOGGER = loggerFor<EchoServer>()

        @Throws(Exception::class)
        @JvmStatic
        fun main(args: Array<String>) {
            val host = args.getOrElse(0) { "localhost" }
            val port = args.getOrElse(1) { "8080" }.toInt()

            EchoServer(host, port).start()
        }
    }
}
```

```
class EchoClient(private val host: String, private val port: Int) {
    fun start() {
        val client = TcpClient.create(host, port)
        val handler = BiFunction<NettyInbound, NettyOutbound, Publisher<Void>> { inbound, outbound ->
            inbound.receive()
                    .asString(StandardCharsets.UTF_8)
                    .doOnNext {
                        LOGGER.info("Client received: {}.", it)
                        if (it == "bye") {
                            LOGGER.info("Stopping client.", it)
                            inbound.context().dispose()
                            outbound.context().dispose()
                        }
                    }
                    .doOnError { LOGGER.error(it.message, it) }
                    .subscribe()

            outbound.options {t -> t.flushOnEach(false)}
                    .sendString(Flux.fromArray(arrayOf("hi", "hello", "netty", "bye"))
                            .delayElements(Duration.ofMillis(100)))
                    .neverComplete()
        }
        client.startAndAwait(handler)
    }

    companion object {
        val LOGGER = loggerFor<EchoClient>()

        @Throws(Exception::class)
        @JvmStatic
        fun main(args: Array<String>) {
            val host = args.getOrElse(0) { "localhost" }
            val port = args.getOrElse(1) { "8080" }.toInt()
            EchoClient(host, port).start()
        }
    }
}
```

Please excuse us for the delay in answering.
I would suggest to use [Gitter](https://gitter.im/reactor/reactor) for further questions and discussions thus the whole community will benefit from this.

Regards,
Violeta

**Comment by simbo1905** [comment]
If anyone is looking for how to make an Echo TCP echo client-server with reactor-netty here is is what I was able to figure out https://gist.github.com/simbo1905/213e1bf966dc80e04349977a1bcb7b00

I worked that out by looking at the completed branch of the workshop repo at https://github.com/violetagg/reactor-netty-workshop
