### ISSUE TITLE
Access Logs contents enhancement

### ISSUE THREAD

**Issue by blackwizard1812** [reactor/reactor-netty#434]
#301  lately brought support of access logs.
I would need a couple of more information in those logs:
- request port
- time taken (in milliseconds)

Furthermore, I don't get the point in having the date time with force formatting in the logged message while the logger will add it with user-configured format.

**Comment by violetagg** [comment]
> Furthermore, I don't get the point in having the date time with force formatting in the logged message while the logger will add it with user-configured format.

With the first implementation we support `CLF`, so we use the specified date format.
When you use this log configuration https://github.com/reactor/reactor-netty/blob/master/src/test/resources/logback.xml#L35 you will receive exactly `CLF`.

I created another enhancement #436 so that we provide more options for the access log.
