### ISSUE TITLE
Feature Request: Custom DNS Resolver

### ISSUE THREAD

**Issue by bcelenk** [reactor/reactor-netty#501]
Currently, `TcpClient` uses `InetSocketAddressUtil` for resolving DNS addresses. `InetSocketAddressUtil#createInetSocketAddress` creates a new `InetSocketAddress`. `InetSocketAddress`'s constuctor always returns the first cached `InetAddress` within the `getByName` method.

There should be a way to provide a custom DNS resolver for the `TcpClient`. Because, while using reactor-netty in `spring-cloud-gateway` it only uses a single node of the load balancer which is AWS's ALB in our case.

**Comment by mulderbaba** [comment]
@violetagg can we add this to `0.7.x Backlog` if possible?

**Comment by violetagg** [comment]
@mulderbaba sure

**Comment by PyvesB** [comment]
> Currently, `TcpClient` uses `InetSocketAddressUtil` for resolving DNS addresses. `InetSocketAddressUtil#createInetSocketAddress` creates a new `InetSocketAddress`. `InetSocketAddress`'s constuctor always returns the first cached `InetAddress` within the `getByName` method.

This may have changed since you first posted this issue, but as far as I can tell, `TcpClient` uses `InetSocketAddressUtil` to create unresolved addresses. No cache will be used at that point. DNS resolution itself seems to be performed at a later stage, when Netty's `InetSocketAddressResolver` class is called.

Implementing a custom DNS resolver in `TcpClient` should already be possible with a bit of code similar to the following:
```
DnsNameResolverBuilder dnsResolverBuilder = new DnsNameResolverBuilder()
        .channelFactory(() -> new EpollDatagramChannel())
        .resolveCache(new DefaultDnsCache());
TcpClient tcpClient = TcpClient.create().resolver(new DnsAddressResolverGroup(dnsResolverBuilder));
HttpClient client = HttpClient.from(tcpClient);
...
```

The above `DnsNameResolverBuilder` class comes for the _netty-dns-resolver_ library and can be customised in quite a fine-grained manner. 

Hopefully this can help others stumbling upon this issue. 😉

**Comment by violetagg** [comment]
There is an API for providing custom DNS resolver in addition to that Reactor Netty now uses Netty DNS Resolver #1252

**Comment by amitkhurana92** [comment]
In my current logic I'm using host file for dns mapping e.g. 
echo "172.227.127.277    domain.com" >> /etc/hosts; cat /etc/hosts

But I want to resolve this dynamically without specifying this mapping in the host file. 

@PyvesB can you help me in this?
