### ISSUE TITLE
The HttpClient always connect to 80 port

### ISSUE THREAD

**Issue by Sparta2** [reactor/reactor-netty#762]
### Expected behavior
The `HttpClient` should connect the port which I specified by `port()`
### Actual behavior
The `HttpClient` always connect 80 port even I call `port(90)`.
The only way to specified port is `uri()` , just like `uri("http://127.0.0.1:90/test")`
### Reactor Netty version
reactor-netty:0.9.0.M2
### JVM version (e.g. `java -version`)
1.8.0_201
### OS version (e.g. `uname -a`)
`Windows7 64`

**Comment by violetagg** [comment]
@Sparta2 please provide example

All Reactor Netty tests use the `port()` when connecting.

**Comment by Sparta2** [comment]
just like this :
**HttpClient.create()
                .port(90)
                .put()
                .uri("http://172.31.15.54/t")
                .send(ByteBufFlux.fromString(Mono.just("test")))
                .responseContent()
                .aggregate()
                .asString()
                .block();**

then the exception is :
`reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /172.31.15.54:80
`
I have tried several approaches including :
`uri("/172.31.15.54/t")`,`uri("172.31.15.54/t")`and `baseUrl("172.31.15.54")`,all of these connected to the 80 port.

but `uri("/172.31.15.54:90/t")` works fine

and if i connect to the localhost ,the client will connect to the correct port,just like:
**HttpClient.create()
                .port(90)
                .put()
                .uri("/t")
                .send(ByteBufFlux.fromString(Mono.just("test")))
                .responseContent()
                .aggregate()
                .asString()
                .block();**

and the exception becomes : 
`reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:90`

in addition to those above,i have tried the `addressSupplier` too.
if i called `.addressSupplier(() -> new InetSocketAddress("172.31.15.54",90))` and `.uri("172.31.15.54/t")` then the client still connect to 80port.
buf if i called `.addressSupplier(() -> new InetSocketAddress("172.31.15.54",90))` and `.uri("/t")` then the client will connect to the right port.

**Comment by Sparta2** [comment]
I didn't start the server so there will be always a exception when connect.I think it is convenient to see which port the client connected...

**Comment by Sparta2** [comment]
And i read your `HttpClientTest`. When use the `createHttpClientForContextWithPort` method , the servers were listen 0 port. When use the `createHttpClientForContextWithAddress` method , the `uri` didn't specified the host, just like one of the correct situation above.

**Comment by violetagg** [comment]
@Sparta2 

When`baseUrl`/`url` are absolute they will override the `port`/`host` configuration. So in the examples below `port`/`host` configuration will be overridden and the client will try to connect to `172.31.15.54:80`:

```
HttpClient.create()
                .port(90)
                .uri("http://172.31.15.54/t")
```

```
HttpClient.create()
                .port(90)
                .uri("172.31.15.54/t")
```

```
HttpClient.create()
                .port(90)
                .baseUrl("http://172.31.15.54")
                .uri("/t")
```

```
HttpClient.create()
                .port(90)
                .baseUrl("172.31.15.54")
                .uri("/t")
```

The snippet below will try to connect to `http://localhost:90/172.31.15.54/t` because the url is not absolute:

```
HttpClient.create()
                .port(90)
                .uri("/172.31.15.54/t")
```

**Comment by Sparta2** [comment]
Thanks for explanation

**Comment by gtomassi** [comment]
@Sparta2 
I just hit this same issue as well and was having a difficult time debugging until I found this post. So thank you!

@violetagg
Appreciate the explanation. As someone that's built/designed/worked with quite a few networking libraries, I'd say that it's very confusing and not intuitive that if someone specifies a host address with no port, and separately specifies a port, they don't get that combo. I can't really see any good reason for this? Ultimately something underneath is establishing a socket with a HOST/PORT combo, and theres no reason why the port wouldn't specify the port of that socket. 

Additionally, I tried your example (that should work) with a domain name instead of an IP, and it doesn't work. I'm sure thats the expected behavior, but once again very confusing and a user can't resolve a path forward without being highly proficient in this library's inner workings.

If we hit this, lots of people will inevitably spend time debugging the same issue. And since the library has the benefit of being at an early stage, I'd definitely suggest giving some critical thought to the design decisions here. 

Thank you!
