### ISSUE TITLE
Add Global Option to Disable Chunked Transfer

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#94]
Currently in order to disable chunked transfer encoding, each request must be modified setting `chunkedTransfer`.  If you want to code an application that is connecting to a network device that cannot support chunked transfer you must disable this option for each and every request.

Instead of requiring this for each request there should be a global option to disable this behavior for all uses of a specific `HttpClient`.

**Comment by violetagg** [comment]
Fixed by #261

**Comment by kimec** [comment]
Shouldn't this be backported to 0.7.*? In its current form, WebFlux client is unusable with any HTTP service which does not support "chunked" transfer encoding.
This kind of defeats the purpose why one would want to migrate to WebFlux client in heterogeneous scenarios (scenarios where not all services are Java/Spring/WebFlux based).
It is certainly a show stopper for us, since we need to integrate with legacy CGI HTTP service which does not support "chunked" encoding.

**Comment by yate** [comment]
@violetagg is this still an option? I don't see it anymore in https://github.com/reactor/reactor-netty/blob/master/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java

**Comment by violetagg** [comment]
> @violetagg is this still an option? I don't see it anymore in https://github.com/reactor/reactor-netty/blob/master/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java

If you specify `Content-Length` it will disable the chunked transfer
https://github.com/reactor/reactor-netty/blob/3528badfa032195e8325f35ba351e993cf186a9a/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java#L67-L69
